apiVersion: v1
kind: Service
metadata:
  name: unus-motus
spec:
  clusterIP: None
  selector:
    app: unus-motus
  ports:
    - port: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unus-motus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: unus-motus
  template:
    metadata:
      labels:
        app: unus-motus
    spec:
      containers:
        - name: unus-motus
          image: ghcr.io/oliver-ni/unus-motus-leaderboard:latest
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: unus-motus
                  key: db-uri
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: unus-motus
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: api.unusmotus.com
      http:
        paths:
          - backend:
              serviceName: unus-motus
              servicePort: 4000
